In [1]:
import tensorflow as tf
import keras
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import numpy as np
import os
import shutil
import sklearn
import cv2
import csv
import math
#import image
from skimage.io import imread
from PIL import Image
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
import matplotlib.image as mpimg
#导入图表库
import matplotlib.pyplot as plt
from keras import models
from keras import layers
from keras import applications
from keras.layers import Dense
from keras.models import Sequential
from sklearn.preprocessing import normalize

from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing import image
from keras.applications.vgg19 import VGG19

from keras.applications.vgg19 import preprocess_input

from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing   

from sklearn.model_selection import KFold
from keras.utils import plot_model
# PCA 主成分分析
from sklearn.decomposition import PCA
from keras.callbacks import TensorBoard
print("hello tensorflow")

Using TensorFlow backend.


hello tensorflow


## 读取数据

In [2]:
# 读取数据
X = pd.read_csv(open("../../emotionData/finalData.csv",encoding='utf-8'))
#X = pd.DataFrame(X)
X = X[0:239999]
X = X.values

print(X.shape)
print(X)

(239999, 1024)
[[0.31910929 0.52602024 0.47184321 ... 0.39789196 0.36649874 0.35365854]
 [0.31910929 0.52602024 0.47184321 ... 0.08695652 0.08312343 0.0804878 ]
 [0.31910929 0.52602024 0.47184321 ... 0.39262187 0.395466   0.39878049]
 ...
 [0.64525379 0.91699595 0.65415632 ... 0.47694335 0.59823678 0.60487805]
 [0.55993044 0.40413241 0.47403153 ... 0.75625824 0.69269521 0.59512195]
 [0.64658885 0.30753055 0.35559861 ... 0.50988142 0.5302267  0.47560976]]


In [3]:
with open('../../emotionData/s25w-r-n.CSV',"rt", encoding="utf-8") as vsvfile:
    reader = csv.reader(vsvfile)
    y = [row[128] for row in reader]
#y = pd.DataFrame(y)
y = y[1:]
y = y[0:239999]
#
y = pd.DataFrame(y)
print(y.shape)
print(y)

(239999, 1)
               0
0       0.136147
1       0.058372
2       0.126422
3       0.108744
4       0.110896
5        0.17498
6       0.134798
7       0.133093
8       0.114068
9        0.08394
10      0.138001
11      0.162281
12      0.024871
13      0.049312
14      0.074712
15      0.027434
16      0.127124
17      0.051743
18      0.084803
19        0.0248
20      0.105067
21      0.141144
22       0.08615
23      0.135191
24      0.152599
25      0.168492
26      0.074377
27      0.190048
28       0.03048
29      0.059181
...          ...
239969  0.057701
239970    0.0552
239971  0.081782
239972  0.071156
239973  0.058882
239974  0.074815
239975  0.113112
239976  0.050515
239977  0.144805
239978  0.125566
239979  0.127759
239980  0.143141
239981   0.10808
239982  0.099706
239983  0.124837
239984  0.119256
239985  0.093946
239986   0.09057
239987   0.14971
239988  0.136218
239989  0.102945
239990  0.127501
239991  0.071766
239992  0.073368
239993  0.144539
239994  0.101104
23

In [4]:
from keras.layers.normalization import BatchNormalization

model = Sequential()

model.add(Dense(1024, input_dim=1024, activation='relu'))
model.add(keras.layers.normalization.BatchNormalization(axis=-1, 
                                              momentum=0.99, 
                                              epsilon=0.001, 
                                              center=True, 
                                              scale=True, 
                                              beta_initializer='zeros', 
                                              gamma_initializer='ones',
                                              ))

model.add(Dense(1024, input_dim=1024, activation='relu'))
model.add(keras.layers.normalization.BatchNormalization(axis=-1, 
                                              momentum=0.99, 
                                              epsilon=0.001, 
                                              center=True, 
                                              scale=True, 
                                              beta_initializer='zeros', 
                                              gamma_initializer='ones',
                                              ))


model.add(Dense(512, input_dim=1024, activation='relu'))
model.add(keras.layers.normalization.BatchNormalization(axis=-1, 
                                              momentum=0.99, 
                                              epsilon=0.001, 
                                              center=True, 
                                              scale=True, 
                                              beta_initializer='zeros', 
                                              gamma_initializer='ones',
                                              ))

model.add(Dense(512, input_dim=512, activation='relu'))
model.add(keras.layers.normalization.BatchNormalization(axis=-1, 
                                              momentum=0.99, 
                                              epsilon=0.001, 
                                              center=True, 
                                              scale=True, 
                                              beta_initializer='zeros', 
                                              gamma_initializer='ones',
                                              ))

model.add(Dense(256, input_dim=512, activation='relu'))
model.add(keras.layers.normalization.BatchNormalization(axis=-1, 
                                              momentum=0.99, 
                                              epsilon=0.001, 
                                              center=True, 
                                              scale=True, 
                                              beta_initializer='zeros', 
                                              gamma_initializer='ones',
                                              ))

model.add(Dense(256, input_dim=256, activation='relu'))
model.add(keras.layers.normalization.BatchNormalization(axis=-1, 
                                              momentum=0.99, 
                                              epsilon=0.001, 
                                              center=True, 
                                              scale=True, 
                                              beta_initializer='zeros', 
                                              gamma_initializer='ones',
                                              ))

model.add(Dense(128, input_dim=256, activation='relu'))
model.add(keras.layers.normalization.BatchNormalization(axis=-1, 
                                              momentum=0.99, 
                                              epsilon=0.001, 
                                              center=True, 
                                              scale=True, 
                                              beta_initializer='zeros', 
                                              gamma_initializer='ones',
                                              ))

model.add(Dense(128, input_dim=128, activation='relu'))
model.add(keras.layers.normalization.BatchNormalization(axis=-1, 
                                              momentum=0.99, 
                                              epsilon=0.001, 
                                              center=True, 
                                              scale=True, 
                                              beta_initializer='zeros', 
                                              gamma_initializer='ones',
                                              ))

model.add(Dense(64, activation='relu'))
model.add(keras.layers.normalization.BatchNormalization(axis=-1, 
                                              momentum=0.99, 
                                              epsilon=0.001, 
                                              center=True, 
                                              scale=True, 
                                              beta_initializer='zeros', 
                                              gamma_initializer='ones',
                                              ))

model.add(Dense(64, activation='relu'))
model.add(keras.layers.normalization.BatchNormalization(axis=-1, 
                                              momentum=0.99, 
                                              epsilon=0.001, 
                                              center=True, 
                                              scale=True, 
                                              beta_initializer='zeros', 
                                              gamma_initializer='ones',
                                              ))

model.add(Dense(32, activation='relu'))
model.add(keras.layers.normalization.BatchNormalization(axis=-1, 
                                              momentum=0.99, 
                                              epsilon=0.001, 
                                              center=True, 
                                              scale=True, 
                                              beta_initializer='zeros', 
                                              gamma_initializer='ones',
                                              ))

model.add(Dense(16, activation='relu'))
model.add(keras.layers.normalization.BatchNormalization(axis=-1, 
                                              momentum=0.99, 
                                              epsilon=0.001, 
                                              center=True, 
                                              scale=True, 
                                              beta_initializer='zeros', 
                                              gamma_initializer='ones',
                                              ))

model.add(Dense(16, activation='relu'))
model.add(keras.layers.normalization.BatchNormalization(axis=-1, 
                                              momentum=0.99, 
                                              epsilon=0.001, 
                                              center=True, 
                                              scale=True, 
                                              beta_initializer='zeros', 
                                              gamma_initializer='ones',
                                              ))

model.add(Dense(8, activation='relu'))
model.add(keras.layers.normalization.BatchNormalization(axis=-1, 
                                              momentum=0.99, 
                                              epsilon=0.001, 
                                              center=True, 
                                              scale=True, 
                                              beta_initializer='zeros', 
                                              gamma_initializer='ones',
                                              ))

model.add(Dense(8, activation='relu'))
model.add(keras.layers.normalization.BatchNormalization(axis=-1, 
                                              momentum=0.99, 
                                              epsilon=0.001, 
                                              center=True, 
                                              scale=True, 
                                              beta_initializer='zeros', 
                                              gamma_initializer='ones',
                                              ))


model.add(Dense(1, activation='sigmoid'))

Instructions for updating:
Colocations handled automatically by placer.


In [5]:
from keras import backend as K

from sklearn import metrics

def mre(y_true, y_pred):
    return K.mean(K.sum(K.abs(100*K.ones_like(y_true) * (y_true - y_pred) / y_true)))


def pearson_r(y_true, y_pred):
    x = y_true
    y = y_pred
    mx = K.mean(x, axis=0)
    my = K.mean(y, axis=0)
    xm, ym = x - mx, y - my
    r_num = K.sum(xm * ym)
    x_square_sum = K.sum(xm * xm)
    y_square_sum = K.sum(ym * ym)
    r_den = K.sqrt(x_square_sum * y_square_sum)
    r = r_num / r_den
    return K.mean(r)

def r_square_final(y_true, y_pred):
    SSR = K.mean(K.square(y_pred-K.mean(y_true)),axis=-1)
    SST = K.mean(K.square(y_true-K.mean(y_true)),axis=-1)
    return SSR/SST

In [6]:
model.compile(
    loss='mean_squared_error', 
    optimizer='adam',
    metrics=['mean_squared_error',
             'mean_absolute_error',
             'mean_absolute_percentage_error',
             'mean_squared_logarithmic_error',
             r_square_final,
            # metrics.r2_score,
            # metrics.r2_score,
             pearson_r,
             mre]
)

print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1024)              1049600   
_________________________________________________________________
batch_normalization_1 (Batch (None, 1024)              4096      
_________________________________________________________________
dense_2 (Dense)              (None, 1024)              1049600   
_________________________________________________________________
batch_normalization_2 (Batch (None, 1024)              4096      
_________________________________________________________________
dense_3 (Dense)              (None, 512)               524800    
_________________________________________________________________
batch_normalization_3 (Batch (None, 512)               2048      
_________________________________________________________________
dense_4 (Dense)              (None, 512)               262656    
__________

In [7]:
callbacks_list = [
    # 训练可视化
    keras.callbacks.TensorBoard(
        log_dir='./fit_Euclidean_Distance_logs',  # log 目录
        histogram_freq=0,  # 按照何等频率（epoch）来计算直方图，0为不计算
        #batch_size=32,     # 用多大量的数据计算直方图
        write_graph=True,  # 是否存储网络结构图
        write_grads=True, # 是否可视化梯度直方图
        write_images=True,# 是否可视化参数
        embeddings_freq=0,
        embeddings_layer_names=None, 
        embeddings_metadata=None),
    
    # 训练自动更改学习率
    keras.callbacks.ReduceLROnPlateau(
        monitor='val_mean_squared_error', 
        factor=0.2,
        patience=5,
        verbose=1,
        mode='min',
        min_delta=0.0001, 
        cooldown=0, 
        min_lr=0.0001),
    
    # 当被监测的数量不再提升，则停止训练
    keras.callbacks.EarlyStopping(
        monitor='val_mean_squared_error', 
        min_delta=0, 
        patience=30, 
        verbose=1, 
        mode='min', 
        baseline=None, 
        restore_best_weights=False)

]

In [8]:
import keras.backend.tensorflow_backend as KTF #进行配置，每个GPU使用80%上限现存


#os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"  # 使用编号为0号的GPU

config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.8 # 每个GPU现存上届控制在80%以内
session = tf.Session(config=config) # 设置session KTF.set_session(session )
#设置session
KTF.set_session(session )

#注意：
#config.gpu_options.per_process_gpu_memory_fraction = 0.8 # 每个GPU现存上届控制在80%以内
#设置GPU使用上限，可以有效避免显存不足而导致的jupyter 问题:
#The kernel appears to have died. It will restart automatically

In [9]:
keras.backend.get_session().run(tf.global_variables_initializer())


his=model.fit(
    X,
    y,
    
    validation_split=0.1,
    epochs=70,
    batch_size=1024,
    
    shuffle=True,
    verbose=1,
    
    
    callbacks=callbacks_list
)

Instructions for updating:
Use tf.cast instead.
Train on 215999 samples, validate on 24000 samples
Epoch 1/70
215999/215999 [==============================] - 49s 228us/step - loss: 0.0717 - mean_squared_error: 0.0717 - mean_absolute_error: 0.2337 - mean_absolute_percentage_error: 1374.4046 - mean_squared_logarithmic_error: 0.0436 - r_square_final: 3257622.9715 - pearson_r: 0.0011 - mre: inf - val_loss: 0.0196 - val_mean_squared_error: 0.0196 - val_mean_absolute_error: 0.1077 - val_mean_absolute_percentage_error: 127.2291 - val_mean_squared_logarithmic_error: 0.0122 - val_r_square_final: 155431989.2690 - val_pearson_r: 0.0038 - val_mre: 129137.2310
Epoch 2/70
215999/215999 [==============================] - 45s 210us/step - loss: 0.0136 - mean_squared_error: 0.0136 - mean_absolute_error: 0.0709 - mean_absolute_percentage_error: 933.3313 - mean_squared_logarithmic_error: 0.0077 - r_square_final: 2850470.4360 - pearson_r: 0.0024 - mre: inf - val_loss: 0.0108 - val_mean_squared_error: 0.0

215999/215999 [==============================] - 58s 268us/step - loss: 0.0038 - mean_squared_error: 0.0038 - mean_absolute_error: 0.0305 - mean_absolute_percentage_error: 547.3598 - mean_squared_logarithmic_error: 0.0022 - r_square_final: 1025.2936 - pearson_r: 0.0016 - mre: inf - val_loss: 9.6808e-04 - val_mean_squared_error: 9.6808e-04 - val_mean_absolute_error: 0.0256 - val_mean_absolute_percentage_error: 31.8819 - val_mean_squared_logarithmic_error: 8.0073e-04 - val_r_square_final: 2293671.2011 - val_pearson_r: 0.0017 - val_mre: 32332.4173

Epoch 00015: ReduceLROnPlateau reducing learning rate to 0.00020000000949949026.
Epoch 16/70
215999/215999 [==============================] - 58s 270us/step - loss: 0.0038 - mean_squared_error: 0.0038 - mean_absolute_error: 0.0304 - mean_absolute_percentage_error: 532.0457 - mean_squared_logarithmic_error: 0.0021 - r_square_final: 699.1226 - pearson_r: 0.0052 - mre: inf - val_loss: 9.6731e-04 - val_mean_squared_error: 9.6731e-04 - val_mean_abso

215999/215999 [==============================] - 57s 266us/step - loss: 0.0038 - mean_squared_error: 0.0038 - mean_absolute_error: 0.0304 - mean_absolute_percentage_error: 559.5720 - mean_squared_logarithmic_error: 0.0021 - r_square_final: 519.1628 - pearson_r: 0.0103 - mre: inf - val_loss: 9.6495e-04 - val_mean_squared_error: 9.6495e-04 - val_mean_absolute_error: 0.0256 - val_mean_absolute_percentage_error: 31.8880 - val_mean_squared_logarithmic_error: 7.9819e-04 - val_r_square_final: 2495158.2088 - val_pearson_r: -5.4146e-04 - val_mre: 32340.6457
Epoch 30/70
215999/215999 [==============================] - 59s 273us/step - loss: 0.0038 - mean_squared_error: 0.0038 - mean_absolute_error: 0.0304 - mean_absolute_percentage_error: 564.6437 - mean_squared_logarithmic_error: 0.0021 - r_square_final: 2912182.8517 - pearson_r: 0.0107 - mre: inf - val_loss: 9.6046e-04 - val_mean_squared_error: 9.6046e-04 - val_mean_absolute_error: 0.0255 - val_mean_absolute_percentage_error: 31.7579 - val_mea

Epoch 44/70
215999/215999 [==============================] - 62s 285us/step - loss: 0.0038 - mean_squared_error: 0.0038 - mean_absolute_error: 0.0304 - mean_absolute_percentage_error: 535.9999 - mean_squared_logarithmic_error: 0.0021 - r_square_final: 361.9913 - pearson_r: 0.0073 - mre: inf - val_loss: 9.6875e-04 - val_mean_squared_error: 9.6875e-04 - val_mean_absolute_error: 0.0257 - val_mean_absolute_percentage_error: 32.0318 - val_mean_squared_logarithmic_error: 8.0146e-04 - val_r_square_final: 2382709.7445 - val_pearson_r: 0.0114 - val_mre: 32486.5286
Epoch 45/70
215999/215999 [==============================] - 61s 281us/step - loss: 0.0038 - mean_squared_error: 0.0038 - mean_absolute_error: 0.0304 - mean_absolute_percentage_error: 571.5855 - mean_squared_logarithmic_error: 0.0021 - r_square_final: 729.6203 - pearson_r: 0.0070 - mre: inf - val_loss: 9.4502e-04 - val_mean_squared_error: 9.4502e-04 - val_mean_absolute_error: 0.0253 - val_mean_absolute_percentage_error: 31.3588 - val_

Epoch 59/70
215999/215999 [==============================] - 60s 279us/step - loss: 0.0037 - mean_squared_error: 0.0037 - mean_absolute_error: 0.0304 - mean_absolute_percentage_error: 509.2613 - mean_squared_logarithmic_error: 0.0021 - r_square_final: 2656.9021 - pearson_r: 0.0054 - mre: inf - val_loss: 9.5811e-04 - val_mean_squared_error: 9.5811e-04 - val_mean_absolute_error: 0.0255 - val_mean_absolute_percentage_error: 31.7451 - val_mean_squared_logarithmic_error: 7.9246e-04 - val_r_square_final: 2488896.3661 - val_pearson_r: 0.0014 - val_mre: 32195.5282
Epoch 60/70
215999/215999 [==============================] - 60s 279us/step - loss: 0.0037 - mean_squared_error: 0.0037 - mean_absolute_error: 0.0304 - mean_absolute_percentage_error: 564.0049 - mean_squared_logarithmic_error: 0.0021 - r_square_final: 69.7779 - pearson_r: 0.0074 - mre: inf - val_loss: 9.5599e-04 - val_mean_squared_error: 9.5599e-04 - val_mean_absolute_error: 0.0255 - val_mean_absolute_percentage_error: 31.6676 - val_

In [10]:
# calculate predictions

test_X = X
#actual = y

# from keras.models import load_model

# model = load_model('model.h5')
predictions = model.predict(test_X)

In [11]:
# round predictions
B = []
for x in predictions:
    for i in x:
        B.append(i)
        
B = B[1:239999]

In [12]:
actual = y[1:239999]

In [13]:
sum, sum2 = float(0), float(0)
max, mre, res, abres = float(0), float(0), float(0), float(0)

zipped = zip(actual, B)

In [19]:
print("Actual\t\tPredicted\t MRE\t\tRes. Error\tAbs. Res. Error")
for i, j in zipped:
    mre = float(abs(float(i) - float(j))) / float(i)
    res = float(i) - float(j)
    abres = float(abs(res))
    sum = sum + mre
    sum2 = sum2 + res
    if (abs(float(i) - float(j)) / float(i) > max):
        max = float(abs(float(i) - float(j))) / float(i)
    stringI = '{:.4f}'.format(float(i))
    stringJ = '{:.4f}'.format(float(j))
    #print (stringI, "\t\t", stringJ, "\t", '{:.4f}'.format(mre), "\t", '{:.4f}'.format(res), "\t", '{:.4f}'.format(abres))

Actual		Predicted	 MRE		Res. Error	Abs. Res. Error


In [20]:
def mean_squared_error_byself(y_true,y_predict):
    assert len(y_true) == len(y_predict), \
        "the size of y_true must be equal to be the size of y_predict"
    return np.sum((y_true - y_predict) ** 2 ) / len(y_true)

def root_mean_squared_error_byself(y_true,y_predict):
    """计算y_true和y_predict之间的RMES"""
    assert len(y_true) == len(y_predict), \
        "the size of y_true must be equal to be the size of y_predict"
    return math.sqrt(np.sum((y_true - y_predict) ** 2 ) / len(y_true))

def mean_absolute_error_byself(y_true,y_predict):
    """计算y_true和y_predict之间的MAE"""
    assert len(y_true) == len(y_predict), \
        "the size of y_true must be equal to be the size of y_predict"
    return np.sum(np.absolute(y_true - y_predict)) / len(y_true)

print("Mean Absolute Error      ", mean_absolute_error_byself(np.array(actual, dtype = float) , np.array(B, dtype = float)))
print("Mean Squared Error       ", mean_squared_error_byself(np.array(actual, dtype = float) , np.array(B, dtype = float)))
print("Root Mean Square Error : ", root_mean_squared_error_byself(np.array(actual, dtype = float) , np.array(B, dtype = float)))


MemoryError: 

In [18]:
print("\nMean Magnitude of Relative Error (MMRE) : ", sum / len(actual))
print("MaxMRE :                 ", max)
print("Explained Variance Score ", metrics.explained_variance_score(np.array(actual, dtype = float) , np.array(B, dtype = float)))
print("Mean Absolute Error      ", metrics.mean_absolute_error(np.array(actual, dtype = float) , np.array(B, dtype = float)))
print("Mean Squared Error       ", metrics.mean_squared_error(np.array(actual, dtype = float) , np.array(B, dtype = float)))
print("Median Absolute Error    ", metrics.median_absolute_error(np.array(actual, dtype = float) , np.array(B, dtype = float)))
print("R-Square Score           ", metrics.r2_score(np.array(actual, dtype = float) , np.array(B, dtype = float)))
print("Root Mean Square Error : ", (sum2 / len(B)) ** (1 / 2))


Mean Magnitude of Relative Error (MMRE) :  0.0
MaxMRE :                  0.0
Explained Variance Score  -0.0005160613297856553
Mean Absolute Error       0.029836204371257585
Mean Squared Error        0.003469103991219168
Median Absolute Error     0.02354980006980896
R-Square Score            -0.0006859557688050355
Root Mean Square Error :  0.0
